# Generated by Django 3.1.3 on 2023-06-04 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='contents',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questions',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='Relations',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='rightorwrong',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Relations',
        ),
        migrations.RemoveField(
            model_name='question',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='question',
            name='gradepoint',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='is_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
